# Generated by Django 4.2.20 on 2025-03-07 22:37

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('coupons', '0001_initial'),
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, verbose_name='First name')),
                ('first_name_en', models.CharField(max_length=50, null=True, verbose_name='First name')),
                ('first_name_fr', models.CharField(max_length=50, null=True, verbose_name='First name')),
                ('first_name_es', models.CharField(max_length=50, null=True, verbose_name='First name')),
                ('last_name', models.CharField(max_length=50, verbose_name='Last name')),
                ('last_name_en', models.CharField(max_length=50, null=True, verbose_name='Last name')),
                ('last_name_fr', models.CharField(max_length=50, null=True, verbose_name='Last name')),
                ('last_name_es', models.CharField(max_length=50, null=True, verbose_name='Last name')),
                ('email', models.EmailField(max_length=254, verbose_name='E-mail')),
                ('email_en', models.EmailField(max_length=254, null=True, verbose_name='E-mail')),
                ('email_fr', models.EmailField(max_length=254, null=True, verbose_name='E-mail')),
                ('email_es', models.EmailField(max_length=254, null=True, verbose_name='E-mail')),
                ('phone', models.CharField(blank=True, help_text='Contact phone number', max_length=16)),
                ('phone_en', models.CharField(blank=True, help_text='Contact phone number', max_length=16, null=True)),
                ('phone_fr', models.CharField(blank=True, help_text='Contact phone number', max_length=16, null=True)),
                ('phone_es', models.CharField(blank=True, help_text='Contact phone number', max_length=16, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('created_en', models.DateTimeField(auto_now_add=True, null=True)),
                ('created_fr', models.DateTimeField(auto_now_add=True, null=True)),
                ('created_es', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('updated_en', models.DateTimeField(auto_now=True, null=True)),
                ('updated_fr', models.DateTimeField(auto_now=True, null=True)),
                ('updated_es', models.DateTimeField(auto_now=True, null=True)),
                ('paid', models.BooleanField(default=False)),
                ('paid_en', models.BooleanField(default=False)),
                ('paid_fr', models.BooleanField(default=False)),
                ('paid_es', models.BooleanField(default=False)),
                ('braintree_id', models.CharField(blank=True, max_length=150)),
                ('braintree_id_en', models.CharField(blank=True, max_length=150, null=True)),
                ('braintree_id_fr', models.CharField(blank=True, max_length=150, null=True)),
                ('braintree_id_es', models.CharField(blank=True, max_length=150, null=True)),
                ('arrival_date_time', models.DateTimeField(null=True, verbose_name='Date & time for Arrival to CC-floreana')),
                ('arrival_date_time_en', models.DateTimeField(null=True, verbose_name='Date & time for Arrival to CC-floreana')),
                ('arrival_date_time_fr', models.DateTimeField(null=True, verbose_name='Date & time for Arrival to CC-floreana')),
                ('arrival_date_time_es', models.DateTimeField(null=True, verbose_name='Date & time for Arrival to CC-floreana')),
                ('departure_date_time', models.DateTimeField(null=True, verbose_name='Date & time for Departure to CC-floreana')),
                ('departure_date_time_en', models.DateTimeField(null=True, verbose_name='Date & time for Departure to CC-floreana')),
                ('departure_date_time_fr', models.DateTimeField(null=True, verbose_name='Date & time for Departure to CC-floreana')),
                ('departure_date_time_es', models.DateTimeField(null=True, verbose_name='Date & time for Departure to CC-floreana')),
                ('agree_term', models.BooleanField(default=False, verbose_name='I accept the terms and conditions of this services.')),
                ('agree_term_en', models.BooleanField(default=False, verbose_name='I accept the terms and conditions of this services.')),
                ('agree_term_fr', models.BooleanField(default=False, verbose_name='I accept the terms and conditions of this services.')),
                ('agree_term_es', models.BooleanField(default=False, verbose_name='I accept the terms and conditions of this services.')),
                ('total', models.DecimalField(blank=True, decimal_places=2, max_digits=1000, null=True)),
                ('total_en', models.DecimalField(blank=True, decimal_places=2, max_digits=1000, null=True)),
                ('total_fr', models.DecimalField(blank=True, decimal_places=2, max_digits=1000, null=True)),
                ('total_es', models.DecimalField(blank=True, decimal_places=2, max_digits=1000, null=True)),
                ('discount', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('discount_en', models.IntegerField(default=0, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('discount_fr', models.IntegerField(default=0, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('discount_es', models.IntegerField(default=0, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('coupon', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='coupons.coupon')),
                ('coupon_en', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='coupons.coupon')),
                ('coupon_es', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='coupons.coupon')),
                ('coupon_fr', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='coupons.coupon')),
            ],
            options={
                'verbose_name': 'Reserva Online',
                'verbose_name_plural': 'Reservas Online',
                'ordering': ('-created',),
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='shop.product')),
            ],
        ),
    ]
