# Generated by Django 3.2.13 on 2022-09-09 00:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ('-created',), 'verbose_name': 'Reserva Online', 'verbose_name_plural': 'Reservas Online'},
        ),
    ]
