# Generated by Django 3.2.15 on 2022-10-05 22:17

from django.db import migrations, models
import phone_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_alter_order_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='agree_term',
            field=models.BooleanField(default=False, verbose_name='I accept the terms and conditions of this services.'),
        ),
        migrations.AddField(
            model_name='order',
            name='arrival',
            field=models.DateField(null=True, verbose_name='Date for Arrival to CC-floreana'),
        ),
        migrations.AddField(
            model_name='order',
            name='departure',
            field=models.DateField(null=True, verbose_name='Date for departure from CC-floreana'),
        ),
        migrations.AddField(
            model_name='order',
            name='phone',
            field=phone_field.models.PhoneField(blank=True, help_text='Contact phone number', max_length=31),
        ),
        migrations.AlterField(
            model_name='order',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='E-mail'),
        ),
        migrations.AlterField(
            model_name='order',
            name='first_name',
            field=models.CharField(max_length=50, verbose_name='First name'),
        ),
        migrations.AlterField(
            model_name='order',
            name='last_name',
            field=models.CharField(max_length=50, verbose_name='Last name'),
        ),
    ]
