# Generated by Django 3.2.15 on 2022-10-05 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_auto_20221005_1717'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='arrival',
            field=models.DateTimeField(null=True, verbose_name='Date for Arrival to CC-floreana'),
        ),
        migrations.AlterField(
            model_name='order',
            name='departure',
            field=models.DateTimeField(null=True, verbose_name='Date for departure from CC-floreana'),
        ),
    ]
