# Generated by Django 3.2.15 on 2022-10-05 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_auto_20221005_1759'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='time_arrival',
            field=models.DateTimeField(null=True, verbose_name='Time for Arrival to CC-floreana'),
        ),
        migrations.AddField(
            model_name='order',
            name='time_departure',
            field=models.DateTimeField(null=True, verbose_name='Time for departure from CC-floreana'),
        ),
    ]
