# Generated by Django 3.2.15 on 2022-10-05 23:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_auto_20221005_1808'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='time_arrival',
        ),
        migrations.RemoveField(
            model_name='order',
            name='time_departure',
        ),
    ]
