# Generated by Django 3.2.15 on 2022-10-06 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_auto_20221005_1836'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='phone',
            field=models.CharField(blank=True, help_text='Contact phone number', max_length=16),
        ),
    ]
