# Generated by Django 3.2.15 on 2022-10-06 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_alter_order_phone'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='arrival',
            new_name='end_departure_date',
        ),
        migrations.AddField(
            model_name='order',
            name='end_departure_time',
            field=models.DateTimeField(null=True, verbose_name='Time for Arrival to CC-floreana'),
        ),
        migrations.AddField(
            model_name='order',
            name='start_arrival_date',
            field=models.DateTimeField(null=True, verbose_name='Date for Arrival to CC-floreana'),
        ),
        migrations.AddField(
            model_name='order',
            name='start_arrival_time',
            field=models.DateTimeField(null=True, verbose_name='Time for Arrival to CC-floreana'),
        ),
    ]
