# Generated by Django 3.2.15 on 2022-10-06 05:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_auto_20221005_2202'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='end_departure_date',
            new_name='arrival_date_time',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='start_arrival_date',
            new_name='departure_date_time',
        ),
        migrations.RemoveField(
            model_name='order',
            name='departure',
        ),
        migrations.RemoveField(
            model_name='order',
            name='end_departure_time',
        ),
        migrations.RemoveField(
            model_name='order',
            name='start_arrival_time',
        ),
    ]
