# Generated by Django 3.2.15 on 2022-10-06 22:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_order_total'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='address',
        ),
        migrations.RemoveField(
            model_name='order',
            name='city',
        ),
        migrations.RemoveField(
            model_name='order',
            name='postal_code',
        ),
    ]
