# Generated by Django 4.2.20 on 2025-03-07 22:37

from django.db import migrations, models
import django.db.models.deletion
import parler.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=200, null=True)),
                ('name_en', models.CharField(db_index=True, max_length=200, null=True)),
                ('name_fr', models.CharField(db_index=True, max_length=200, null=True)),
                ('name_es', models.CharField(db_index=True, max_length=200, null=True)),
                ('slug', models.SlugField(max_length=200, null=True, unique=True)),
                ('slug_en', models.SlugField(max_length=200, null=True, unique=True)),
                ('slug_fr', models.SlugField(max_length=200, null=True, unique=True)),
                ('slug_es', models.SlugField(max_length=200, null=True, unique=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='categories/%Y/%m/%d')),
                ('image_en', models.ImageField(blank=True, null=True, upload_to='categories/%Y/%m/%d')),
                ('image_fr', models.ImageField(blank=True, null=True, upload_to='categories/%Y/%m/%d')),
                ('image_es', models.ImageField(blank=True, null=True, upload_to='categories/%Y/%m/%d')),
                ('salidas', models.DateTimeField(null=True)),
                ('salidas_en', models.DateTimeField(null=True)),
                ('salidas_fr', models.DateTimeField(null=True)),
                ('salidas_es', models.DateTimeField(null=True)),
                ('desde', models.CharField(max_length=200, null=True)),
                ('desde_en', models.CharField(max_length=200, null=True)),
                ('desde_fr', models.CharField(max_length=200, null=True)),
                ('desde_es', models.CharField(max_length=200, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('description_en', models.TextField(blank=True, null=True)),
                ('description_fr', models.TextField(blank=True, null=True)),
                ('description_es', models.TextField(blank=True, null=True)),
                ('detail', models.FileField(null=True, upload_to='tours/%Y/%m/%d')),
                ('detail_en', models.FileField(null=True, upload_to='tours/%Y/%m/%d')),
                ('detail_fr', models.FileField(null=True, upload_to='tours/%Y/%m/%d')),
                ('detail_es', models.FileField(null=True, upload_to='tours/%Y/%m/%d')),
                ('terms', models.TextField(blank=True, null=True)),
                ('terms_en', models.TextField(blank=True, null=True)),
                ('terms_fr', models.TextField(blank=True, null=True)),
                ('terms_es', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'category',
                'verbose_name_plural': 'categories',
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=200)),
                ('name_en', models.CharField(db_index=True, max_length=200, null=True)),
                ('name_fr', models.CharField(db_index=True, max_length=200, null=True)),
                ('name_es', models.CharField(db_index=True, max_length=200, null=True)),
                ('slug', models.SlugField(max_length=200)),
                ('slug_en', models.SlugField(max_length=200, null=True)),
                ('slug_fr', models.SlugField(max_length=200, null=True)),
                ('slug_es', models.SlugField(max_length=200, null=True)),
                ('description', models.TextField(blank=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('available', models.BooleanField(default=True)),
                ('item1', models.CharField(max_length=200, null=True)),
                ('item2', models.CharField(max_length=200, null=True)),
                ('item3', models.CharField(max_length=200, null=True)),
                ('image', models.ImageField(blank=True, upload_to='products/%Y/%m/%d')),
                ('image_en', models.ImageField(blank=True, null=True, upload_to='products/%Y/%m/%d')),
                ('image_fr', models.ImageField(blank=True, null=True, upload_to='products/%Y/%m/%d')),
                ('image_es', models.ImageField(blank=True, null=True, upload_to='products/%Y/%m/%d')),
                ('image_2', models.ImageField(blank=True, upload_to='products/%Y/%m/%d')),
                ('image_3', models.ImageField(blank=True, upload_to='products/%Y/%m/%d')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='shop.category')),
            ],
            options={
                'abstract': False,
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
    ]
