# Generated by Django 3.2.15 on 2022-10-06 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_auto_20220818_1633'),
    ]

    operations = [
        migrations.AddField(
            model_name='categorytranslation',
            name='terms',
            field=models.TextField(blank=True),
        ),
    ]
