# Generated by Django 3.2.15 on 2022-10-06 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_categorytranslation_detail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorytranslation',
            name='detail',
            field=models.FileField(null=True, upload_to='tours/%Y/%m/%d'),
        ),
    ]
