# Generated by Django 4.2.19 on 2025-03-05 01:38

from django.db import migrations, models
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_smartbusinessmedia_info_banner_title16_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='home',
            name='banner_title',
        ),
        migrations.RemoveField(
            model_name='home',
            name='info1',
        ),
        migrations.RemoveField(
            model_name='home',
            name='info2',
        ),
        migrations.RemoveField(
            model_name='home',
            name='info3',
        ),
        migrations.RemoveField(
            model_name='home',
            name='info4',
        ),
        migrations.RemoveField(
            model_name='home',
            name='info5',
        ),
        migrations.RemoveField(
            model_name='home',
            name='info6',
        ),
        migrations.RemoveField(
            model_name='home',
            name='info7',
        ),
        migrations.RemoveField(
            model_name='home',
            name='info8',
        ),
        migrations.RemoveField(
            model_name='home',
            name='info9',
        ),
        migrations.RemoveField(
            model_name='home',
            name='numero_coffe',
        ),
        migrations.RemoveField(
            model_name='home',
            name='numero_experiencia',
        ),
        migrations.RemoveField(
            model_name='home',
            name='numero_horas',
        ),
        migrations.RemoveField(
            model_name='home',
            name='numero_wins',
        ),
        migrations.RemoveField(
            model_name='home',
            name='product_1',
        ),
        migrations.RemoveField(
            model_name='home',
            name='product_2',
        ),
        migrations.RemoveField(
            model_name='home',
            name='product_3',
        ),
        migrations.RemoveField(
            model_name='home',
            name='product_4',
        ),
        migrations.RemoveField(
            model_name='home',
            name='product_5',
        ),
        migrations.RemoveField(
            model_name='home',
            name='product_6',
        ),
        migrations.RemoveField(
            model_name='home',
            name='product_description_1',
        ),
        migrations.RemoveField(
            model_name='home',
            name='product_description_2',
        ),
        migrations.RemoveField(
            model_name='home',
            name='product_description_3',
        ),
        migrations.RemoveField(
            model_name='home',
            name='product_description_4',
        ),
        migrations.RemoveField(
            model_name='home',
            name='product_description_5',
        ),
        migrations.RemoveField(
            model_name='home',
            name='product_description_6',
        ),
        migrations.RemoveField(
            model_name='home',
            name='slogan',
        ),
        migrations.RemoveField(
            model_name='home',
            name='slogan_descriptcion',
        ),
        migrations.RemoveField(
            model_name='home',
            name='team_1',
        ),
        migrations.RemoveField(
            model_name='home',
            name='team_2',
        ),
        migrations.RemoveField(
            model_name='home',
            name='team_3',
        ),
        migrations.RemoveField(
            model_name='home',
            name='team_4',
        ),
        migrations.RemoveField(
            model_name='home',
            name='team_descrp_1',
        ),
        migrations.RemoveField(
            model_name='home',
            name='team_descrp_2',
        ),
        migrations.RemoveField(
            model_name='home',
            name='team_descrp_3',
        ),
        migrations.RemoveField(
            model_name='home',
            name='team_descrp_4',
        ),
        migrations.AddField(
            model_name='home',
            name='TS_date1',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Tearsheet-1'),
        ),
        migrations.AddField(
            model_name='home',
            name='TS_date10',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Tearsheet-10'),
        ),
        migrations.AddField(
            model_name='home',
            name='TS_date11',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Tearsheet-11'),
        ),
        migrations.AddField(
            model_name='home',
            name='TS_date12',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Tearsheet-12'),
        ),
        migrations.AddField(
            model_name='home',
            name='TS_date13',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Tearsheet-13'),
        ),
        migrations.AddField(
            model_name='home',
            name='TS_date14',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Tearsheet-14'),
        ),
        migrations.AddField(
            model_name='home',
            name='TS_date15',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Tearsheet-15'),
        ),
        migrations.AddField(
            model_name='home',
            name='TS_date16',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Tearsheet-16'),
        ),
        migrations.AddField(
            model_name='home',
            name='TS_date17',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Tearsheet-17'),
        ),
        migrations.AddField(
            model_name='home',
            name='TS_date18',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Tearsheet-18'),
        ),
        migrations.AddField(
            model_name='home',
            name='TS_date19',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Tearsheet-19'),
        ),
        migrations.AddField(
            model_name='home',
            name='TS_date2',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Tearsheet-2'),
        ),
        migrations.AddField(
            model_name='home',
            name='TS_date20',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Tearsheet-20'),
        ),
        migrations.AddField(
            model_name='home',
            name='TS_date3',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Tearsheet-3'),
        ),
        migrations.AddField(
            model_name='home',
            name='TS_date4',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Tearsheet-4'),
        ),
        migrations.AddField(
            model_name='home',
            name='TS_date5',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Tearsheet-5'),
        ),
        migrations.AddField(
            model_name='home',
            name='TS_date6',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Tearsheet-6'),
        ),
        migrations.AddField(
            model_name='home',
            name='TS_date7',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Tearsheet-7'),
        ),
        migrations.AddField(
            model_name='home',
            name='TS_date8',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Tearsheet-8'),
        ),
        migrations.AddField(
            model_name='home',
            name='TS_date9',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Tearsheet-9'),
        ),
        migrations.AddField(
            model_name='home',
            name='TS_info10',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Tearsheet-10 info'),
        ),
        migrations.AddField(
            model_name='home',
            name='TS_info11',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Tearsheet-11 info'),
        ),
        migrations.AddField(
            model_name='home',
            name='TS_info12',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Tearsheet-12 info'),
        ),
        migrations.AddField(
            model_name='home',
            name='TS_info13',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Tearsheet-13 info'),
        ),
        migrations.AddField(
            model_name='home',
            name='TS_info14',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Tearsheet-14 info'),
        ),
        migrations.AddField(
            model_name='home',
            name='TS_info15',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Tearsheet-15 info'),
        ),
        migrations.AddField(
            model_name='home',
            name='TS_info16',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Tearsheet-16 info'),
        ),
        migrations.AddField(
            model_name='home',
            name='TS_info17',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Tearsheet-17 info'),
        ),
        migrations.AddField(
            model_name='home',
            name='TS_info18',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Tearsheet-18 info'),
        ),
        migrations.AddField(
            model_name='home',
            name='TS_info19',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Tearsheet-19 info'),
        ),
        migrations.AddField(
            model_name='home',
            name='TS_info20',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Tearsheet-20 info'),
        ),
        migrations.AddField(
            model_name='home',
            name='TS_info7',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Tearsheet-7 info'),
        ),
        migrations.AddField(
            model_name='home',
            name='TS_info8',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Tearsheet-8 info'),
        ),
        migrations.AddField(
            model_name='home',
            name='TS_info9',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Tearsheet-9 info'),
        ),
        migrations.AddField(
            model_name='home',
            name='banner_title11',
            field=wagtail.fields.RichTextField(blank=True, verbose_name='Titulo de galeria-4  '),
        ),
        migrations.AddField(
            model_name='home',
            name='bio',
            field=wagtail.fields.RichTextField(blank=True, verbose_name='rseña bibliografica'),
        ),
        migrations.AlterField(
            model_name='home',
            name='TS_info1',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Tearsheet-1 info'),
        ),
        migrations.AlterField(
            model_name='home',
            name='TS_info2',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Tearsheet-2 info'),
        ),
        migrations.AlterField(
            model_name='home',
            name='TS_info3',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Tearsheet-3 info'),
        ),
        migrations.AlterField(
            model_name='home',
            name='TS_info4',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Tearsheet-4 info'),
        ),
        migrations.AlterField(
            model_name='home',
            name='TS_info5',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Tearsheet-5 info'),
        ),
        migrations.AlterField(
            model_name='home',
            name='TS_info6',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Tearsheet-6 info'),
        ),
        migrations.AlterField(
            model_name='home',
            name='banner_title10',
            field=wagtail.fields.RichTextField(blank=True, verbose_name='Titulo de galeria-4  '),
        ),
        migrations.AlterField(
            model_name='home',
            name='banner_title4',
            field=wagtail.fields.RichTextField(blank=True, verbose_name='Titulo de galeria-1 '),
        ),
        migrations.AlterField(
            model_name='home',
            name='banner_title5',
            field=wagtail.fields.RichTextField(blank=True, verbose_name='Titulo de galeria-2  '),
        ),
        migrations.AlterField(
            model_name='home',
            name='banner_title6',
            field=wagtail.fields.RichTextField(blank=True, verbose_name='Titulo de galeria-3  '),
        ),
        migrations.AlterField(
            model_name='home',
            name='banner_title7',
            field=wagtail.fields.RichTextField(blank=True, verbose_name='Titulo de galeria-4  '),
        ),
        migrations.AlterField(
            model_name='home',
            name='banner_title8',
            field=wagtail.fields.RichTextField(blank=True, verbose_name='Titulo de galeria-4  '),
        ),
        migrations.AlterField(
            model_name='home',
            name='banner_title9',
            field=wagtail.fields.RichTextField(blank=True, verbose_name='Titulo de galeria-4  '),
        ),
        migrations.AlterField(
            model_name='home',
            name='consulta',
            field=wagtail.fields.RichTextField(blank=True, verbose_name='Mensaje para que nos consulten por el formulario'),
        ),
        migrations.AlterField(
            model_name='home',
            name='custom_title',
            field=models.CharField(blank=True, help_text='Reescribe el  Titulo de la publicacion ', max_length=100, null=True),
        ),
    ]
